{
   "CVE_data_meta" : {
      "ASSIGNER" : "lpardo@redhat.com",
      "ID" : "CVE-2018-10878",
      "STATE" : "PUBLIC"
   },
   "affects" : {
      "vendor" : {
         "vendor_data" : [
            {
               "product" : {
                  "product_data" : [
                     {
                        "product_name" : "kernel",
                        "version" : {
                           "version_data" : [
                              {
                                 "version_value" : "n/a"
                              }
                           ]
                        }
                     }
                  ]
               },
               "vendor_name" : "[UNKNOWN]"
            }
         ]
      }
   },
   "data_format" : "MITRE",
   "data_type" : "CVE",
   "data_version" : "4.0",
   "description" : {
      "description_data" : [
         {
            "lang" : "eng",
            "value" : "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause an out-of-bounds write and a denial of service or unspecified other impact is possible by mounting and operating a crafted ext4 filesystem image."
         }
      ]
   },
   "impact" : {
      "cvss" : [
         [
            {
               "vectorString" : "4.8/CVSS:3.0/AV:P/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:H",
               "version" : "3.0"
            }
         ]
      ]
   },
   "problemtype" : {
      "problemtype_data" : [
         {
            "description" : [
               {
                  "lang" : "eng",
                  "value" : "CWE-787"
               }
            ]
         }
      ]
   },
   "references" : {
      "reference_data" : [
         {
            "name" : "http://patchwork.ozlabs.org/patch/929237/",
            "refsource" : "CONFIRM",
            "url" : "http://patchwork.ozlabs.org/patch/929237/"
         },
         {
            "name" : "http://patchwork.ozlabs.org/patch/929238/",
            "refsource" : "CONFIRM",
            "url" : "http://patchwork.ozlabs.org/patch/929238/"
         },
         {
            "name" : "https://bugzilla.kernel.org/show_bug.cgi?id=199865",
            "refsource" : "CONFIRM",
            "url" : "https://bugzilla.kernel.org/show_bug.cgi?id=199865"
         },
         {
            "name" : "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10878",
            "refsource" : "CONFIRM",
            "url" : "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10878"
         },
         {
            "name" : "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=77260807d1170a8cf35dbb06e07461a655f67eee",
            "refsource" : "CONFIRM",
            "url" : "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=77260807d1170a8cf35dbb06e07461a655f67eee"
         },
         {
            "name" : "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=819b23f1c501b17b9694325471789e6b5cc2d0d2",
            "refsource" : "CONFIRM",
            "url" : "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=819b23f1c501b17b9694325471789e6b5cc2d0d2"
         }
      ]
   }
}
