{
    "impact": {
        "cvss": [
            [
                {
                    "vectorString": "5.9/CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
                    "version": "3.0"
                }
            ]
        ]
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "Ansible 2.5 prior to 2.5.5, and 2.4 prior to 2.4.5, do not honor the no_log task flag for failed tasks. When the no_log flag has been used to protect sensitive data passed to a task from being logged, and that task does not run successfully, Ansible will expose sensitive data in log files and on the terminal of the user running Ansible."
            }
        ]
    },
    "data_type": "CVE",
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "Ansible 2.4.5"
                                        },
                                        {
                                            "version_value": "Ansible 2.5.5"
                                        }
                                    ]
                                },
                                "product_name": "ansible"
                            }
                        ]
                    },
                    "vendor_name": "[UNKNOWN]"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-532"
                    }
                ]
            }
        ]
    },
    "data_version": "4.0",
    "references": {
        "reference_data": [
            {
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10855"
            }
        ]
    },
    "CVE_data_meta": {
        "ID": "CVE-2018-10855",
        "ASSIGNER": "lpardo@redhat.com"
    }
}
