{
    "impact": {
        "cvss": [
            [
                {
                    "vectorString": "5.3/CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
                    "version": "3.0"
                }
            ]
        ]
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "In fuse before versions 2.9.8, 3.2.5 fusermount is vulnerable to a restriction bypass when SELinux is active. This allows non-root users to mount a FUSE file system with the 'allow_other' mount option regardless of whether 'user_allow_other' is set in the fuse configuration. An attacker may use this flaw to mount a FUSE file system, accessible by other users, and trick them into accessing files on that file system, possibly causing Denial of Service or other unspecified effects."
            }
        ]
    },
    "data_type": "CVE",
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "fuse 2.9.8"
                                        },
                                        {
                                            "version_value": "fuse 3.2.5"
                                        }
                                    ]
                                },
                                "product_name": "fuse"
                            }
                        ]
                    },
                    "vendor_name": "[UNKNOWN]"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-285"
                    }
                ]
            }
        ]
    },
    "data_version": "4.0",
    "references": {
        "reference_data": [
            {
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10906",
                "refsource": "CONFIRM",
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10906"
            }
        ]
    },
    "CVE_data_meta": {
        "ID": "CVE-2018-10906",
        "ASSIGNER": "lpardo@redhat.com"
    }
}
