{
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
        "ID": "CVE-2020-1700",
        "ASSIGNER": "darunesh@redhat.com"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "vendor_name": "[UNKNOWN]",
                    "product": {
                        "product_data": [
                            {
                                "product_name": "ceph",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "14.2.4-125.el8cp"
                                        },
                                        {
                                            "version_value": "14.2.4-51.el7cp"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-400"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1700",
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1700",
                "refsource": "CONFIRM"
            }
        ]
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "A flaw was found in the way the Ceph RGW Beast front-end handles unexpected disconnects. An authenticated attacker can abuse this flaw by making multiple disconnect attempts resulting in a permanent leak of a socket connection by radosgw. This flaw could lead to a denial of service condition by pile up of CLOSE_WAIT sockets, eventually leading to the exhaustion of available resources, preventing legitimate users from connecting to the system."
            }
        ]
    },
    "impact": {
        "cvss": [
            [
                {
                    "vectorString": "6.5/CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                    "version": "3.0"
                }
            ]
        ]
    }
}