{
   "CVE_data_meta" : {
      "ASSIGNER" : "cve@mitre.org",
      "ID" : "CVE-2011-1922",
      "STATE" : "PUBLIC"
   },
   "affects" : {
      "vendor" : {
         "vendor_data" : [
            {
               "product" : {
                  "product_data" : [
                     {
                        "product_name" : "n/a",
                        "version" : {
                           "version_data" : [
                              {
                                 "version_value" : "n/a"
                              }
                           ]
                        }
                     }
                  ]
               },
               "vendor_name" : "n/a"
            }
         ]
      }
   },
   "data_format" : "MITRE",
   "data_type" : "CVE",
   "data_version" : "4.0",
   "description" : {
      "description_data" : [
         {
            "lang" : "eng",
            "value" : "daemon/worker.c in Unbound 1.x before 1.4.10, when debugging functionality and the interface-automatic option are enabled, allows remote attackers to cause a denial of service (assertion failure and daemon exit) via a crafted DNS request that triggers improper error handling."
         }
      ]
   },
   "problemtype" : {
      "problemtype_data" : [
         {
            "description" : [
               {
                  "lang" : "eng",
                  "value" : "n/a"
               }
            ]
         }
      ]
   },
   "references" : {
      "reference_data" : [
         {
            "url" : "http://unbound.nlnetlabs.nl/downloads/CVE-2011-1922.txt"
         },
         {
            "url" : "http://lists.fedoraproject.org/pipermail/package-announce/2011-June/061243.html"
         },
         {
            "url" : "http://www.kb.cert.org/vuls/id/531342"
         },
         {
            "url" : "http://www.securityfocus.com/bid/47986"
         },
         {
            "url" : "http://osvdb.org/72750"
         },
         {
            "url" : "http://secunia.com/advisories/44865"
         },
         {
            "url" : "https://exchange.xforce.ibmcloud.com/vulnerabilities/67645"
         }
      ]
   }
}
